Editorial clarifications
oauth-wg/oauth-identity-chaining pull request #115
Opened 2024-12-06 17:20 UTC by PieterKas

Attempt at addressing issue #107

2024-12-06 17:45 UTC, kburgin3 requested changes
The (Appendix, (#Example)) include two additional

should be (with the "s" at the end of include)

The (Appendix, (#Example)) includes two additional

2024-12-06 17:46 UTC, kburgin3 requested changes
Also should be a "s" in (Appendix, (#Examples))

2024-12-16 13:21 UTC, PieterKas commented
@kburgin3 I corrected they Typos, can you approve?

2025-01-09 15:26 UTC, kburgin3 approved these changes
Looks good

2025-01-10 13:05 UTC, merged