Add continuous integration example and move use cases to the appendix
oauth-wg/oauth-identity-chaining pull request #78
Opened 2024-02-13 15:44 UTC by arndt-s

* Moves use cases to the appendix
* Adds new continuous integration use case

Let me know what you think!

2024-02-14 23:52 UTC, bc-pi requested changes
Thanks @arndt-s, I've got a small editorial suggestion but otherwise think the use case is definitely a worthwhile addition.

2024-02-14 23:52 UTC, bc-pi commented on draft-ietf-oauth-identity-chaining.md
> +This sections outlines some use cases the authors have identified where identity chaining as described in this document should be used. This section is not complete and other use cases not mentioned
Suggest a minor change in wording here (that also anticipates the likely merge of #76):

```suggestion
This sections outlines some use cases where the identity and authorization chaining described in this document can be applied. This section is not complete and other use cases not mentioned here are also valid.
```

2024-02-14 23:59 UTC, bc-pi approved these changes

2024-02-15 00:01 UTC, bc-pi commented
rendered preview of this PR can be seen https://drafts.oauth.net/oauth-identity-chaining/arndt-s/add-ci-use-case/draft-ietf-oauth-identity-chaining.html

2024-02-15 14:20 UTC, bc-pi commented on draft-ietf-oauth-identity-chaining.md
> +## Continuous integration accessing external resources
per Dr. Kelley W Burgin:

```suggestion
## Continuous Integration Accessing External Resources
```

2024-02-16 09:19 UTC, merged

2024-02-16 11:09 UTC, PieterKas commented on draft-ietf-oauth-identity-chaining.md
> +A continuous integration system needs to access external resources, for example to upload an artifact or to run tests. These resources are protected by different authorization servers. The identity i
replace "fined" with "fine"